" Rafael Robayna's vimrc

set nocompatible        " Use vim rather than vi settings
set shell=bash
set shellpipe=2>/dev/null>

syntax enable           
let mapleader=","       " Set the leader
set encoding=utf-8      " Set default encoding to utf-8
set number              " Enable line numbers
set hlsearch
set showmatch
set incsearch
set ignorecase
set showcmd
set autoindent
set history=1000        " Extend history to 1000 
set splitright          " Opens vertical split right of current window
set splitbelow          " Opens horizontal split below current window
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

" " Vundle Initialization 
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
" Themes
Plugin 'Lucius'
Plugin 'Zenburn'
Plugin 'molokai'
Plugin 'wombat256.vim'
" Tools
Plugin 'The-NERD-tree'
Plugin 'taglist.vim'
Plugin 'Mouse-Toggle'
Plugin 'ctrlp.vim'
Plugin 'vimwiki'
Plugin 'bufexplorer.zip'
Plugin 'fugitive.vim'
Plugin 'bling/vim-airline'
Plugin 'airblade/vim-gitgutter'
Plugin 'ShowMarks'
call vundle#end()
filetype plugin indent on    


" " Set Default Colorscheme
try
    set background=dark
    colorscheme lucius
catch /^Vim\%((\a\+)\)\=:E185/
    set background=light
    colorscheme elflord 
endtry


" " Keyboard Shortcuts
map <C-S-Up> :tabnew<CR>
map <C-S-Right> :tabnext<CR>
map <C-S-Left> :tabprevious<CR>
map <C-S-C> :tabclose<CR>
map <C-S-Down> :NERDTreeToggle<CR>
map <C-n> :NERDTreeToggle<CR>
map <leader>tt :Tlist<CR>
map <leader>nn :NERDTreeToggle<CR>
map <leader>bb :BufExplorer<CR>
map <leader>rc :e ~/.vimrc<CR>
map <leader>rr :source ~/.vimrc<CR>  


" " Plugin: taglist
let tlist_php_settings = 'php;f:functions'
let Tlist_WinWidth = 40
let Tlist_Compact_Format = 1
let Tlist_Use_Right_Window = 1
let rlist_Show_One_File = 1
let Tlist_GainFocus_On_ToggleOpen = 1

" " Plugin: BufExplorer
let g:bufExplorerDefaultHelp=0
let g:bufExplorerDisableDefaultKeyMapping=1
let g:bufExplorerDetailedHelp=0
let g:bufExplorerFindActive=1
let g:bufExplorerShowTabBuffer=1
let g:bufExplorerSortBy='number'

" " Plugin: NERDtree
let NERDTreeChDirMode = 0
let NERDTreeQuitOnOpen = 1
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.pyc','\~$','\.swo$','\.swp$','\.git','\.hg','\.svn','\.bzr']

" " Plugin: Showmarks
let g:showmarks_enable=0
let g:showmarks_textlower="\t"
let g:showmarks_textupper=">"
let g:showmarks_textother=">"
let g:showmarks_hlline_lower=1
let g:showmarks_hlline_upper=0
let g:showmarks_hlline_other=0
