# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
install gnu-sed --default-names
# Install Bash 4
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before running `chsh`.
install bash
install bash-completion
# Install wget with IRI support
install wget --enable-iri
# Install more recent versions of some OS X tools
install vim --with-lua --override-system-vi
install homebrew/dupes/grep
install homebrew/php/php55 --with-gmp
# PHP Tools
install homebrew/php/phpunit
install php-code-sniffer
# Other useful binaries
install git
install tmux
install composer
install maven
install node
install ctags
install automake
install autoconf
install atk
install ack
install bfg
install imagemagick --with-webp
install p7zip
install rename
install tree
install webkit2png
install xpdf
install watch
install jsawk
install xz
# Fuse
install osxfuse
install sshfs
# Network Tools
install tcpflow
install nmap
install ngrep
install htop-osx
install iftop
install w3m
# Local Cache and Proxies
install dnsmasq
install squid
install privoxy

# Remove outdated versions from the cellar
cleanup
